#!/bin/bash

# Build ARM64-v8a APK Script for Echo Seeker
# This script builds a release APK for arm64-v8a architecture and moves it to the releases folder

set -e  # Exit on error

echo "🚀 Starting ARM64-v8a APK build process..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Get project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

# Create releases directory if it doesn't exist
RELEASES_DIR="$PROJECT_ROOT/releases"
if [ ! -d "$RELEASES_DIR" ]; then
    echo -e "${BLUE}📁 Creating releases directory...${NC}"
    mkdir -p "$RELEASES_DIR"
fi

# Get version from package.json
VERSION=$(node -p "require('./package.json').version || '1.0.0'")
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

echo -e "${BLUE}📦 Version: $VERSION${NC}"
echo -e "${BLUE}🕐 Timestamp: $TIMESTAMP${NC}"

# Check if android folder exists, if not run expo prebuild
if [ ! -d "$PROJECT_ROOT/android" ]; then
    echo -e "${BLUE}🔧 Android project not found. Running expo prebuild...${NC}"
    npx expo prebuild -p android --clean
fi

# Navigate to android directory
cd "$PROJECT_ROOT/android"

# Clean previous builds (only clean if build directory exists)
if [ -d "app/build" ]; then
    echo -e "${BLUE}🧹 Cleaning previous builds...${NC}"
    ./gradlew clean || echo -e "${BLUE}⚠️  Clean had some warnings, continuing...${NC}"
fi

# Build release APK with arm64-v8a only
echo -e "${BLUE}🔨 Building ARM64-v8a release APK...${NC}"
echo -e "${BLUE}   This may take a few minutes...${NC}"

# Build with specific ABI filter
# First, ensure codegen is generated by running a configuration check
./gradlew tasks > /dev/null 2>&1 || true

# Now build the release APK
./gradlew assembleRelease \
    -PreactNativeArchitectures=arm64-v8a \
    --console=plain

# Find the generated APK
APK_PATH="$PROJECT_ROOT/android/app/build/outputs/apk/release/app-release.apk"

if [ ! -f "$APK_PATH" ]; then
    # Try alternative path with architecture name
    APK_PATH="$PROJECT_ROOT/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk"
fi

if [ ! -f "$APK_PATH" ]; then
    echo -e "${RED}❌ Error: APK not found at expected location${NC}"
    echo -e "${RED}   Searched: android/app/build/outputs/apk/release/${NC}"
    exit 1
fi

# Get APK size
APK_SIZE=$(du -h "$APK_PATH" | cut -f1)

# Create descriptive filename
NEW_APK_NAME="echo-seeker-v${VERSION}-arm64-${TIMESTAMP}.apk"
DEST_PATH="$RELEASES_DIR/$NEW_APK_NAME"

# Copy APK to releases folder
echo -e "${BLUE}📋 Copying APK to releases folder...${NC}"
cp "$APK_PATH" "$DEST_PATH"

# Create a symlink to the latest version (optional)
LATEST_LINK="$RELEASES_DIR/echo-seeker-latest-arm64.apk"
rm -f "$LATEST_LINK"
ln -s "$NEW_APK_NAME" "$LATEST_LINK"

# Print success message
echo -e "${GREEN}✅ Build completed successfully!${NC}"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}📱 APK Details:${NC}"
echo -e "${GREEN}   Name: $NEW_APK_NAME${NC}"
echo -e "${GREEN}   Size: $APK_SIZE${NC}"
echo -e "${GREEN}   Location: releases/$NEW_APK_NAME${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}💡 You can also access the latest build at:${NC}"
echo -e "${BLUE}   releases/echo-seeker-latest-arm64.apk${NC}"
echo ""
